-- Supabase Database Schema for Mangify
-- Includes Tables, Indexes, and Row Level Security (RLS) Policies

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--------------------------------------------------
-- 1. Profiles Table
-- Holds profile details for authenticated users.
-- Linked 1:1 with Supabase Auth users.
--------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Allow public read access to profiles" 
    ON public.profiles FOR SELECT 
    USING (true);

CREATE POLICY "Allow individual users to update their profile" 
    ON public.profiles FOR UPDATE 
    USING (auth.uid() = id);

-- Trigger to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id)
    VALUES (NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


--------------------------------------------------
-- 2. Bookmarks Table
-- Track manga bookmarks. Handles both authenticated (UUID)
-- and anonymous (Device UUID string) users.
--------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- auth.uid()::text or anonymous client UUID
    manga_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    -- Prevent duplicate bookmarks of the same manga for a user
    CONSTRAINT unique_user_manga_bookmark UNIQUE (user_id, manga_id)
);

-- Indexes for fast query lookups
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON public.bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_manga ON public.bookmarks(user_id, manga_id);

-- Enable RLS on bookmarks
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

-- Bookmarks Policies
-- 1. Authenticated users can read their own bookmarks
CREATE POLICY "Allow authenticated select own bookmarks" 
    ON public.bookmarks FOR SELECT 
    TO authenticated
    USING (auth.uid()::text = user_id);

-- 2. Authenticated users can insert their own bookmarks
CREATE POLICY "Allow authenticated insert own bookmarks" 
    ON public.bookmarks FOR INSERT 
    TO authenticated
    WITH CHECK (auth.uid()::text = user_id);

-- 3. Authenticated users can delete their own bookmarks
CREATE POLICY "Allow authenticated delete own bookmarks" 
    ON public.bookmarks FOR DELETE 
    TO authenticated
    USING (auth.uid()::text = user_id);

-- 4. Service role (BFF) can perform all operations (automatically bypassed by service_role, but explicit policies can be set if needed)
-- Note: Anonymous users writing via Next.js API endpoints will use the service_role client, bypassing RLS.
-- However, if client direct access is desired for anonymous users, we can add a public policy (requires safety checks).
-- We keep RLS locked to authenticated/service_role to prevent malicious users from writing to other users' rows.


--------------------------------------------------
-- 3. Reading Progress Table
-- Track active reading chapter, page index, and scroll percent.
-- Handles both authenticated (UUID) and anonymous (Device UUID string) users.
--------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reading_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- auth.uid()::text or anonymous client UUID
    manga_id TEXT NOT NULL,
    chapter_id TEXT NOT NULL,
    page_index INTEGER DEFAULT 0 NOT NULL,
    scroll_percent DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    -- Unique constraint to allow upserts on user + manga combos
    CONSTRAINT unique_user_manga_progress UNIQUE (user_id, manga_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_progress_user_id ON public.reading_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_progress_user_manga ON public.reading_progress(user_id, manga_id);

-- Enable RLS on reading progress
ALTER TABLE public.reading_progress ENABLE ROW LEVEL SECURITY;

-- Reading Progress Policies
-- 1. Authenticated users can select own progress
CREATE POLICY "Allow authenticated select own progress" 
    ON public.reading_progress FOR SELECT 
    TO authenticated
    USING (auth.uid()::text = user_id);

-- 2. Authenticated users can insert/update own progress
CREATE POLICY "Allow authenticated insert own progress" 
    ON public.reading_progress FOR INSERT 
    TO authenticated
    WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Allow authenticated update own progress" 
    ON public.reading_progress FOR UPDATE 
    TO authenticated
    USING (auth.uid()::text = user_id)
    WITH CHECK (auth.uid()::text = user_id);

-- 3. Authenticated users can delete own progress
CREATE POLICY "Allow authenticated delete own progress" 
    ON public.reading_progress FOR DELETE 
    TO authenticated
    USING (auth.uid()::text = user_id);
