-- Supabase Database Schema for Mangify
-- Includes Tables, Indexes, and Row Level Security (RLS) Policies

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--------------------------------------------------
-- 0. Manga & Chapters Tables (Catalog Data)
-- Stores metadata and chapter pages.
--------------------------------------------------
CREATE TABLE IF NOT EXISTS public.manga (
    id TEXT PRIMARY KEY, -- Unique ID (e.g. 'webtoon-character-kang-lim')
    title TEXT NOT NULL,
    author TEXT,
    cover TEXT,
    description TEXT,
    genres TEXT[] DEFAULT '{}'::TEXT[] NOT NULL,
    is_original BOOLEAN DEFAULT true NOT NULL,
    popularity INTEGER DEFAULT 0 NOT NULL,
    original_title TEXT,
    artist TEXT,
    status TEXT DEFAULT 'Ongoing'::text,
    manga_type TEXT DEFAULT 'Manhwa'::text,
    release_year INTEGER,
    views_count TEXT DEFAULT '0'::text,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.chapters (
    id TEXT PRIMARY KEY, -- Unique ID (e.g. 'kanglim-ch1')
    manga_id TEXT NOT NULL REFERENCES public.manga(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    pages TEXT[] DEFAULT '{}'::TEXT[] NOT NULL, -- Array of WebP image URLs
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS on catalog tables
ALTER TABLE public.manga ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;

-- Catalog Policies
CREATE POLICY "Allow public read access to manga" 
    ON public.manga FOR SELECT 
    USING (true);

CREATE POLICY "Allow public read access to chapters" 
    ON public.chapters FOR SELECT 
    USING (true);


--------------------------------------------------
-- 1. Profiles Table
-- Holds profile details for authenticated users.
-- Linked 1:1 with Supabase Auth users.
--------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Allow public read access to profiles" 
    ON public.profiles FOR SELECT 
    USING (true);

CREATE POLICY "Allow individual users to update their profile" 
    ON public.profiles FOR UPDATE 
    USING (auth.uid() = id);

-- Trigger to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id)
    VALUES (NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


--------------------------------------------------
-- 2. Bookmarks Table
-- Track manga bookmarks. Handles both authenticated (UUID)
-- and anonymous (Device UUID string) users.
--------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- auth.uid()::text or anonymous client UUID
    manga_id TEXT NOT NULL REFERENCES public.manga(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    -- Prevent duplicate bookmarks of the same manga for a user
    CONSTRAINT unique_user_manga_bookmark UNIQUE (user_id, manga_id)
);

-- Indexes for fast query lookups
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON public.bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_manga ON public.bookmarks(user_id, manga_id);

-- Enable RLS on bookmarks
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

-- Bookmarks Policies
CREATE POLICY "Allow authenticated select own bookmarks" 
    ON public.bookmarks FOR SELECT 
    TO authenticated
    USING (auth.uid()::text = user_id);

CREATE POLICY "Allow authenticated insert own bookmarks" 
    ON public.bookmarks FOR INSERT 
    TO authenticated
    WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Allow authenticated delete own bookmarks" 
    ON public.bookmarks FOR DELETE 
    TO authenticated
    USING (auth.uid()::text = user_id);


--------------------------------------------------
-- 3. Reading Progress Table
-- Track active reading chapter, page index, and scroll percent.
-- Handles both authenticated (UUID) and anonymous (Device UUID string) users.
--------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reading_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- auth.uid()::text or anonymous client UUID
    manga_id TEXT NOT NULL REFERENCES public.manga(id) ON DELETE CASCADE,
    chapter_id TEXT NOT NULL REFERENCES public.chapters(id) ON DELETE CASCADE,
    page_index INTEGER DEFAULT 0 NOT NULL,
    scroll_percent DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    -- Unique constraint to allow upserts on user + manga combos
    CONSTRAINT unique_user_manga_progress UNIQUE (user_id, manga_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_progress_user_id ON public.reading_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_progress_user_manga ON public.reading_progress(user_id, manga_id);

-- Enable RLS on reading progress
ALTER TABLE public.reading_progress ENABLE ROW LEVEL SECURITY;

-- Reading Progress Policies
CREATE POLICY "Allow authenticated select own progress" 
    ON public.reading_progress FOR SELECT 
    TO authenticated
    USING (auth.uid()::text = user_id);

CREATE POLICY "Allow authenticated insert own progress" 
    ON public.reading_progress FOR INSERT 
    TO authenticated
    WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Allow authenticated update own progress" 
    ON public.reading_progress FOR UPDATE 
    TO authenticated
    USING (auth.uid()::text = user_id)
    WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Allow authenticated delete own progress" 
    ON public.reading_progress FOR DELETE 
    TO authenticated
    USING (auth.uid()::text = user_id);


--------------------------------------------------
-- 4. Activity Logs Table
-- Track user events and activities for analytical purposes.
-- Handles both authenticated (UUID) and anonymous (Device UUID string) users.
--------------------------------------------------
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- auth.uid()::text or anonymous client UUID
    event_type TEXT NOT NULL, -- e.g. 'manga_view', 'chapter_read', 'bookmark_toggle', 'search_query', 'auth_action'
    metadata JSONB DEFAULT '{}'::JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Index for fast user activity queries
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON public.activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_event_type ON public.activity_logs(event_type);

-- Enable RLS on activity logs
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Activity Logs Policies
CREATE POLICY "Allow authenticated insert own logs" 
    ON public.activity_logs FOR INSERT 
    TO authenticated
    WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Allow authenticated select own logs" 
    ON public.activity_logs FOR SELECT 
    TO authenticated
    USING (auth.uid()::text = user_id);

